// This file is auto-generated by @hey-api/openapi-ts

export type SignUpRequestDto = {
    email: string;
    password: string;
};

export type SignUpResponseDto = {
    access_token: string;
};

export type SignInRequestDto = {
    email: string;
    password: string;
};

export type SignInResponseDto = {
    access_token: string;
};

export type CreateTaskRequestDto = {
    /**
     * タスクのタイトル
     */
    title: string;
    /**
     * タスクのステータス
     */
    status?: 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';
    /**
     * タスクの期限
     */
    deadline?: string;
};

export type CreateTaskResponseDto = {
    id: string;
    title: string;
    status: 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';
    deadline?: string;
    createdAt: string;
    updatedAt: string;
};

export type AttachmentInDto = {
    id: string;
    filename: string;
    createdAt: string;
};

export type TaskResponseDto = {
    id: string;
    title: string;
    status: 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';
    deadline?: string;
    attachments: Array<AttachmentInDto>;
    createdAt: string;
    updatedAt: string;
};

export type UpdateTaskRequestDto = {
    title?: string;
    status?: 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';
    deadline?: string;
};

export type CreateAttachmentRequestDto = {
    filename: string;
};

export type CreateAttachmentResponseDto = {
    url: string;
    key: string;
};

export type GetAttachmentResponseDto = {
    url: string;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type AuthControllerSignupData = {
    body: SignUpRequestDto;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type AuthControllerSignupResponses = {
    default: SignUpResponseDto;
};

export type AuthControllerSignupResponse = AuthControllerSignupResponses[keyof AuthControllerSignupResponses];

export type AuthControllerSigninData = {
    body: SignInRequestDto;
    path?: never;
    query?: never;
    url: '/auth/signin';
};

export type AuthControllerSigninResponses = {
    default: SignInResponseDto;
};

export type AuthControllerSigninResponse = AuthControllerSigninResponses[keyof AuthControllerSigninResponses];

export type TaskControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type TaskControllerFindAllResponses = {
    default: Array<TaskResponseDto>;
};

export type TaskControllerFindAllResponse = TaskControllerFindAllResponses[keyof TaskControllerFindAllResponses];

export type TaskControllerCreateData = {
    body: CreateTaskRequestDto;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type TaskControllerCreateResponses = {
    default: CreateTaskResponseDto;
};

export type TaskControllerCreateResponse = TaskControllerCreateResponses[keyof TaskControllerCreateResponses];

export type TaskControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type TaskControllerRemoveResponses = {
    default: boolean;
};

export type TaskControllerRemoveResponse = TaskControllerRemoveResponses[keyof TaskControllerRemoveResponses];

export type TaskControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type TaskControllerFindOneResponses = {
    default: TaskResponseDto;
};

export type TaskControllerFindOneResponse = TaskControllerFindOneResponses[keyof TaskControllerFindOneResponses];

export type TaskControllerUpdateData = {
    body: UpdateTaskRequestDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type TaskControllerUpdateResponses = {
    default: TaskResponseDto;
};

export type TaskControllerUpdateResponse = TaskControllerUpdateResponses[keyof TaskControllerUpdateResponses];

export type AttachmentControllerCreateData = {
    body: CreateAttachmentRequestDto;
    path: {
        taskId: string;
    };
    query?: never;
    url: '/attachments/create/{taskId}';
};

export type AttachmentControllerCreateResponses = {
    default: CreateAttachmentResponseDto;
};

export type AttachmentControllerCreateResponse = AttachmentControllerCreateResponses[keyof AttachmentControllerCreateResponses];

export type AttachmentControllerGetDownloadUrlData = {
    body?: never;
    path: {
        attachmentId: string;
    };
    query?: never;
    url: '/attachments/{attachmentId}';
};

export type AttachmentControllerGetDownloadUrlResponses = {
    default: GetAttachmentResponseDto;
};

export type AttachmentControllerGetDownloadUrlResponse = AttachmentControllerGetDownloadUrlResponses[keyof AttachmentControllerGetDownloadUrlResponses];

export type ClientOptions = {
    baseURL: string;
};