// This file is auto-generated by @hey-api/openapi-ts

export type SignUpRequestDto = {
    email: string;
    password: string;
};

export type SignUpResponseDto = {
    access_token: string;
};

export type SignInRequestDto = {
    email: string;
    password: string;
};

export type SignInResponseDto = {
    access_token: string;
};

export type CreateTaskRequestDto = {
    /**
     * タスクのタイトル
     */
    title: string;
};

export type UpdateTaskRequestDto = {
    title?: string;
    isDone?: boolean;
};

export type CreateAttachmentRequestDto = {
    filename: string;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type AuthControllerSignupData = {
    body: SignUpRequestDto;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type AuthControllerSignupResponses = {
    default: SignUpResponseDto;
};

export type AuthControllerSignupResponse = AuthControllerSignupResponses[keyof AuthControllerSignupResponses];

export type AuthControllerSigninData = {
    body: SignInRequestDto;
    path?: never;
    query?: never;
    url: '/auth/signin';
};

export type AuthControllerSigninResponses = {
    default: SignInResponseDto;
};

export type AuthControllerSigninResponse = AuthControllerSigninResponses[keyof AuthControllerSigninResponses];

export type TaskControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type TaskControllerFindAllResponses = {
    200: unknown;
};

export type TaskControllerCreateData = {
    body: CreateTaskRequestDto;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type TaskControllerCreateResponses = {
    201: unknown;
};

export type TaskControllerRemoveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type TaskControllerRemoveResponses = {
    200: unknown;
};

export type TaskControllerFindOneData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type TaskControllerFindOneResponses = {
    200: unknown;
};

export type TaskControllerUpdateData = {
    body: UpdateTaskRequestDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/{id}';
};

export type TaskControllerUpdateResponses = {
    200: unknown;
};

export type AttachmentControllerCreateData = {
    body: CreateAttachmentRequestDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/tasks/{id}/attachments';
};

export type AttachmentControllerCreateResponses = {
    201: unknown;
};

export type ClientOptions = {
    baseURL: string;
};